### PR TITLE
binary jukebox v1

### PR DESCRIPTION
**Pull request by ric96**
Signed-off-by: Sahaj Sarup <sahajsarup@linaro.org>

### CODE REVIEW

**Comment by ric96** [comment]
@K1504296 can you take a look at the Front Matter on Readme?

**Review by TheodoreRTG — COMMENTED** [review]
The front matter looks good! However, if you could add a "src" folder and move binjuke.c there, as well as create an "images" and blogs directory according to the template, that would be appreciated.

**Comment by ric96** [comment]
@K1504296 updated, can you take a look

**Review by TheodoreRTG — APPROVED** [review]
Looks good!

**Pull request merged**
